//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGAPData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRUEBA_GAP_DBEntities : DbContext
    {
        public PRUEBA_GAP_DBEntities()
            : base("name=PRUEBA_GAP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDENT_SUBJECT> STUDENT_SUBJECT { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
    }
}
