//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGAPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SUBJECT
    {
        public int student_id { get; set; }
        public int subject_id { get; set; }
        public decimal grade { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
